apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx-sample
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/library/nginx:alpine
          ports:
            - containerPort: 80
